### ISSUE TITLE
Manage Snapshots: background not redrawn correctly in daylight mode 

### ISSUE THREAD

**Issue by maker99** [EU1KY/Analyzer_EU1KY_CEC_AKF#1]
In menu: Manage Snapshots: 
When daylight mode is selected and viewing a snapshot, the background of the right side of the 
menu stay becomes black when it should have been white.

### how to reproduce: 
1) set "daylight" background (white)
main menu -> Configuration -> Colours/Beep -> daylight -> exit

2) create a snapshot
main menu -> frequency Sweep -> save snapshot -> exit

3) view a snapshot
main menu -> manage shapshots -> select the last snapshot -> show -> exit

### Result: 
the background is black on the right side of the screen, the left side background is white

Expected result: the complete background is white

**Comment by EU1KY** [comment]
Looks like there is some data starvation on the bus during snapshot capture. Will investigate this.

**Comment by EU1KY** [comment]
No. After at least one frequency sweep execution the snapshot looks good. Seems the page buffer that is not yet rendered was saved instead of the active one (there are two page buffers).

**Comment by maker99** [comment]
Hi Yury, 
yes I noticed that behavior as well - you have to make one sweep to get a good screenshot - this is a another bug than the one I meant.

The solution to the fault I found is likely here (untested) and I still have to find out how to do a pull request: 
**Src/analyzer/window/screenshot.c** 
change 
line 598: LCD_FillAll(**BackGrColor**);
and 
line 626: LCD_FillRect(LCD_MakePoint(200, 0), LCD_MakePoint(479, 30), **BackGrColor**);

thanks for your good work!

**Comment by EU1KY** [comment]
Thank you, @maker99 
The fix is in the commit 2130574794fdbe1e2b369ee62927fc68b060c086, please try it.
The issue remains open: still need to fix screenshot from the wrong page buffer in the Frequency Sweep window.

**Comment by maker99** [comment]
I tested the fix in commit 2130574 successfully - the background is now ok in daylight mode. 
thanks again.
